### PR TITLE
Fix and document "private" option

### LINKED ISSUE #1816: "private" option when seeding a torrent?
according to this https://github.com/webtorrent/webtorrent/issues/386, there is a "private" option for the seeded torrent; however, it is not documented. I can clearly see it in the source code also, but Webtorrent API documentation does not mention it.

### PR DESCRIPTION
**Pull request by alxhotel**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[X] Bug fix
[ ] New feature
[X] Other, please explain:
- Add tests

**What changes did you make? (Give an overview)**
- Add the `private` option to the docs of the API.
- Add tests for the `private` option
- Add missing functionality of the `private` option

**Which issue (if any) does this pull request address?**
Fixes #1816 

**Is there anything you'd like reviewers to focus on?**
Let me know if the changes made in `lib/torrent.js` can be improved :)

### CODE REVIEW

File: lib/torrent.js [hunk 1]
```diff
@@ -252,6 +254,14 @@ class Torrent extends EventEmitter {
   _processParsedTorrent (parsedTorrent) {
     this._debugId = parsedTorrent.infoHash.toString('hex').substring(0, 7)
 
+    if (typeof this.private !== 'undefined') {
+      // `private` option overrides default, only if it's defined
+      parsedTorrent.private = this.private
+    } else {
+      // use default value
+      this.private = !!parsedTorrent.private
```
Comment (KayleePop) [inline lib/torrent.js]: The Object.assign below will assign `this.private` to `parsedTorrent.private`, so the else block isn't necessary? Or maybe there's a bug here?

Comment (alxhotel) [reply lib/torrent.js]: Good one! Well, if the parsed torrent is public then `parsedTorrent.private` would be `undefined`. Thus, the variable `this.private` would not be updated in the Object.assign. This line basically forces this update.

File: lib/torrent.js [hunk 2]
```diff
@@ -73,6 +73,8 @@ class Torrent extends EventEmitter {
     this._store = opts.store || FSChunkStore
     this._getAnnounceOpts = opts.getAnnounceOpts
 
+    if (typeof opts.private === 'boolean') this.private = opts.private
```
Comment (KayleePop) [inline lib/torrent.js]: could use a comment saying that `this.private === undefined` when it wasn't passed as an option and otherwise it will overwrite the private field in the torrent file

Otherwise it just looks like you're making sure the input is a boolean instead of relying on it being undefined later

File: lib/torrent.js (hunk 1 above)
Comment (KayleePop) [reply lib/torrent.js]: It would be falsy either way, but I guess having it defined is good? seems fine

File: lib/torrent.js (hunk 2 above)
Comment (alxhotel) [reply lib/torrent.js]: Agreed

File: lib/torrent.js (hunk 1 above)
Comment (alxhotel) [reply lib/torrent.js]: Ok, done. I think your change even improves readability. Thanks :)
